facebook:
    login_page:
        login_form_id: login_form
        login_form_submit_button_attr: name
        login_form_submit_button_val: login
    after_login_page:
        save_login_form_xpath: //form[@action="/login/device-based/update-nonce/"]
        save_login_html_attr: value
        save_login_html_value: OK
    profile_page:
        meta_info_page:
            timeline_link_xpath: .basicNavItems.mfsm.fcg > a:first-child
        timeline_page:
            post_link_xpath: //div[@data-ft='{"tn":"*W"}']/div[2]/a[1]
        post_page:
            id_xpath: //div[@id='m_story_permalink_view']/div/div/@data-ft
            contents_container_xpath: (//div[@data-ft='{"tn":"*s"}'])[1]//*/text()
    fanpage:
        timeline_page:
            post_link_xpath: //div[@data-ft='{"tn":"*W"}']/div[2]/a[1]
        post_page:
            id_xpath: //div[@id='m_story_permalink_view']/div/div/@data-ft
            contents_container_xpath: (//div[@data-ft='{"tn":"*s"}'])[1]//*/text()
