facebook:
    login_page:
        login_form_id: login_form
        login_form_submit_button_attr: name
        login_form_submit_button_val: login
    after_login_page:
        save_login_form_xpath: //form[@action="/login/device-based/update-nonce/"]
        save_login_html_attr: value
        save_login_html_value: OK
    profile_page:
        meta_info_page:
            timeline_link_xpath: .basicNavItems.mfsm.fcg > a:first-child
        timeline_page:
            post_link_xpath: //div[@data-ft='{"tn":"*W"}']/div[2]/a[1]
        post_page:
            id_xpath: //div[@id='m_story_permalink_view']/div/div/@data-ft
            contents_container_xpath: (//div[@data-ft='{"tn":"*s"}'])[1]//*/text()
    fanpage:
        timeline_page:
            post_link_xpath: //div[@data-ft='{"tn":"*W"}']/div[2]/a[1]
            more_post_restrict_text: 'Hiển thị thêm'
        post_page:
            id_xpath: //div[@id='m_story_permalink_view']/div/div/@data-ft
            contents_container_xpath: (//div[@data-ft='{"tn":"*s"}'])[1]//*/text()
            comment_container_dynamic_xpath: '//div[@id=$postIdContainer]/div/div[5]/div'
            next_comment_page_dynamic_xpath: '//*[@id="see_next_{post_id}"]'
            comment_id_relative_xpath: './@id'
            comment_content_relative_xpath: './div/div[1]//text()'
            comment_author_name_relative_xpath: './div/h3/a/text()'
            comment_author_url_relative_xpath: './div/h3/a/@href'
        reaction_page:
            labels_xpath: '//table/tbody/tr/td/div/div/a[position()>1]/img/@alt'
            data_xpath: '//table/tbody/tr/td/div/div/a[position()>1]/span/text()'


    group:
        timeline_page:
            post_link_xpath: //div[@data-ft='{"tn":"*W"}']/div[2]/a[1]
            more_post_restrict_text: 'Hiển thị thêm'
        post_page:
            id_xpath: //div[@id='m_story_permalink_view']/div/div/@data-ft
            contents_container_xpath: (//div[@data-ft='{"tn":"*s"}'])[1]//*/text()
            author_xpath: (//div[@id='m_story_permalink_view']/div/div/div/div//table//a)[last()-1]
            comment_container_dynamic_xpath: '//div[@id=$postIdContainer]/div/div[5]/div'
            next_comment_page_dynamic_xpath: '//*[@id="see_next_{post_id}"]'
            comment_id_relative_xpath: './@id'
            comment_content_relative_xpath: './div/div[1]//text()'
            comment_author_name_relative_xpath: './div/h3/a/text()'
            comment_author_url_relative_xpath: './div/h3/a/@href'
        reaction_page:
            labels_xpath: '//table/tbody/tr/td/div/div/a[position()>1]/img/@alt'
            data_xpath: '//table/tbody/tr/td/div/div/a[position()>1]/span/text()'